-- 0001_core_schema.sql — the existing EveryLeague data model, ported to Postgres.
--
-- This is a PORT, not a redesign. DATA_MODEL.md is authoritative: canonical
-- text ids (MW_BULL, MW_BULL_M1, MW_SL_2627_001, CAF_MW_000123) stay the
-- primary keys, the enum vocabularies are unchanged, and the two schemas —
-- the league tables and the nt_* national-team tables — stay separate, sharing
-- no ids, exactly as they do in the spreadsheet.
--
-- Three conventions run through every table:
--
--   * `ord` preserves SHEET ROW ORDER, and it is load-bearing, not cosmetic.
--     src/adapt.py numbers MatchView.row from the row's position in the
--     Dataset, and src/standings.py and adapt.cup_rounds sort by it; the
--     validator's two-legged-tie pairing walks ds.matches in insertion order
--     to decide which leg is the decider. Postgres has no inherent row order,
--     so every read that rebuilds a tab MUST `order by ord`. Without it,
--     same-date fixtures silently reshuffle on the rendered pages.
--
--   * Nullable FK columns hold NULL for "absent"; every other text column is
--     `not null default ''`. The Python Dataset reads a blank cell as "", so
--     the CSV emitter coalesces NULL -> ''. Keeping that split means only FK
--     columns ever need coalescing, and a NULL can never be mistaken for a
--     real id.
--
--   * Single-row/single-column integrity lives here as constraints; anything
--     needing cross-row or cross-table context stays in validate.py. The
--     mapping to validate.py's numbered checks is noted per constraint.
--
-- RLS is enabled on every table with read-only public policies. No write
-- policy exists yet: until 0002 adds reporters, the only writer is the secret
-- key (which bypasses RLS), used by scripts/import_canonical.py and CI.

begin;

-- ── Shared helpers ───────────────────────────────────────────────────────────

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

comment on function public.set_updated_at() is
  'updated_at maintenance trigger. Empty search_path: it references no objects.';


-- ── clubs ────────────────────────────────────────────────────────────────────
-- The institution (Nyasa Big Bullets). One row per club; a club's squads are
-- rows in `teams`. Never collapse the two.

create table public.clubs (
  club_id             text primary key,
  name                text not null check (name <> ''),
  short_name          text not null default '',
  city                text not null default '',
  region              text not null default '',
  -- Free text, not an integer: 137 of 138 rows are blank and the Dataset
  -- reads it as a string.
  founded             text not null default '',
  crest               text not null default '',
  status              text not null default '',
  successor_club_id   text references public.clubs (club_id),
  notes               text not null default '',
  ord                 bigint generated by default as identity,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

comment on table public.clubs is
  'The club as an institution. Its squads are rows in teams — do not merge.';


-- ── teams ────────────────────────────────────────────────────────────────────
-- A squad of a club. gender + age_group + squad_level live here, so MW_BULL_M1
-- is the men's first team and MW_BULL_W1 the women's.

create table public.teams (
  team_id       text primary key,
  club_id       text not null references public.clubs (club_id),
  gender        text not null check (gender in ('m', 'w')),
  age_group     text not null
                check (age_group in ('senior', 'u20', 'u19', 'u17', 'u16', 'u15')),
  squad_level   integer not null check (squad_level between 1 and 4),
  display_name  text not null check (display_name <> ''),
  -- The old per-league sheet code (SL_BE, CRFA_AR). PUBLIC URLS AND LOGO
  -- FILENAMES ARE KEYED BY THIS — /{slug}/clubs/SL_BE.html is live. 32 of 157
  -- rows are blank, and adapt.py falls back to team_id for those.
  legacy_code   text not null default '',
  status        text not null default '',
  ord           bigint generated by default as identity,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on column public.teams.legacy_code is
  'Public URL and logo key. Changing a value breaks a live page.';


-- ── competitions ─────────────────────────────────────────────────────────────

create table public.competitions (
  competition_id  text primary key,
  country         text not null default '',
  name            text not null check (name <> ''),
  -- league | cup. A cup needs no extra tables: its rounds are matches.stage
  -- values from the knockout vocabulary.
  type            text not null check (type in ('league', 'cup')),
  tier            integer,
  gender          text not null check (gender in ('m', 'w')),
  age_group       text not null
                  check (age_group in ('senior', 'u20', 'u19', 'u17', 'u16', 'u15')),
  region          text not null default '',
  governing_body  text not null default '',
  logo            text not null default '',
  ord             bigint generated by default as identity,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

comment on column public.competitions.age_group is
  'Lowercased so it joins cleanly against teams.age_group; the sheet mixed case.';


-- ── seasons ──────────────────────────────────────────────────────────────────
-- Exactly one row may be status=active. That row — never the system clock — is
-- what the build treats as the current season (dataset.Dataset.active_season).

create table public.seasons (
  season_id   text primary key,
  country     text not null default '',
  label       text not null check (label <> ''),
  start_date  date not null,
  end_date    date not null,
  status      text not null check (status in ('active', 'complete')),
  ord         bigint generated by default as identity,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint seasons_dates_ordered check (start_date <= end_date)
);

-- dataset.active_season() raises unless exactly one row is active. Enforcing
-- "at most one" here turns the silent half of that into a database error;
-- "at least one" stays in Python, where an empty table is also a failure.
create unique index seasons_one_active
  on public.seasons ((status)) where status = 'active';


-- ── competition_seasons ──────────────────────────────────────────────────────
-- One competition in one season. sponsor_name overrides the display name.

create table public.competition_seasons (
  competition_id     text not null references public.competitions (competition_id),
  season_id          text not null references public.seasons (season_id),
  sponsor_name       text not null default '',
  format             text not null default '',
  teams_count        integer check (teams_count >= 0),
  promotion_places   integer check (promotion_places >= 0),
  relegation_places  integer check (relegation_places >= 0),
  points_win         integer not null default 3,
  points_draw        integer not null default 1,
  status             text not null default '',
  ord                bigint generated by default as identity,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  primary key (competition_id, season_id)
);

comment on column public.competition_seasons.sponsor_name is
  'Display-name override. League name = this when non-empty, else competitions.name.';


-- ── entries ──────────────────────────────────────────────────────────────────
-- A team's participation in one competition+season. Standings iterate entries,
-- so a team with zero matches still appears in the table.

create table public.entries (
  entry_id           text primary key,
  competition_id     text not null references public.competitions (competition_id),
  season_id          text not null references public.seasons (season_id),
  team_id            text not null references public.teams (team_id),
  "group"            text not null default '',
  points_adjustment  integer not null default 0,   -- may be negative
  adjustment_reason  text not null default '',
  status             text not null default 'active'
                     check (status in ('active', 'withdrawn', 'expelled')),
  ord                bigint generated by default as identity,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  -- Makes the composite FK on matches below possible, which is what turns
  -- validate.py check 3 into a database guarantee. Verified unique across all
  -- 165 existing rows.
  unique (competition_id, season_id, team_id)
);

comment on column public.entries.status is
  'Blank in the sheet means active; the importer normalizes it.';


-- ── venues ───────────────────────────────────────────────────────────────────

create table public.venues (
  venue_id    text primary key,
  name        text not null check (name <> ''),
  city        text not null default '',
  -- Free text like clubs.founded: 60 of 76 rows are blank.
  capacity    text not null default '',
  ord         bigint generated by default as identity,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);


-- ── players ──────────────────────────────────────────────────────────────────
-- Canonical player identities. CAF_MW_UNKNOWN is a reserved row, not a person:
-- goals whose scorer is not yet identified point at it, and the build keeps
-- them out of scorer rankings while still counting them in team totals.

create table public.players (
  player_id    text primary key,
  full_name    text not null default '',
  known_as     text not null default '',
  dob          date,
  position     text not null default '',
  nationality  text not null default '',
  status       text not null default '',
  ord          bigint generated by default as identity,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.players is
  'Canonical identities only. Reporter-typed names go to goals.reported_player_name '
  'against CAF_MW_UNKNOWN — never create a player row per free-text name.';


-- ── reporters ────────────────────────────────────────────────────────────────
-- Already in the data model (currently zero rows). 0002 extends this with
-- auth_user_id and reporter_assignments rather than adding a parallel
-- profiles/users concept.

create table public.reporters (
  reporter_id     text primary key,
  name            text not null check (name <> ''),
  email           text not null default '',
  affiliation     text not null default '',
  affiliation_id  text not null default '',
  region          text not null default '',
  active          text not null default '',
  public_byline   text not null default '',
  ord             bigint generated by default as identity,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

comment on table public.reporters is
  'Holds email/affiliation, so it gets NO anon read policy. The build reads it '
  'with the secret key.';


-- ── matches ──────────────────────────────────────────────────────────────────

create table public.matches (
  match_id        text primary key,

  -- Unguessable id for reporter deep links (/report/m/<public_id>). Added
  -- ALONGSIDE match_id, which stays the canonical opaque key everywhere else —
  -- per DATA_MODEL.md, ids are never regenerated. Secrecy of this value is not
  -- authorization; the reporter's assignment is.
  public_id       uuid not null unique default gen_random_uuid(),

  competition_id  text not null references public.competitions (competition_id),
  season_id       text not null references public.seasons (season_id),

  -- Free-form md_<n> on leagues; on a type=cup competition it must come from
  -- the knockout vocabulary (r64|r32|r16|qf|sf|final|3p). That rule needs
  -- competitions.type, so it stays in validate.py check 7.
  stage           text not null default '',
  matchday        integer check (matchday >= 0),

  -- NULL = fixture not yet scheduled to a day (876 such rows today). It is the
  -- Malawi calendar date, which is what makes "today's fixtures" a plain
  -- equality test for the reporter home screen.
  date            date,
  -- Kept as text, not `time`: the sheet holds both HH:MM and Sheets' HH:MM:SS
  -- and adapt.clock normalizes either (and anything unreadable) for display.
  -- Always Malawi time — CAT, UTC+2, no DST.
  kickoff         text not null default ''
                  check (kickoff = '' or kickoff ~ '^[0-9]{1,2}:[0-9]{2}(:[0-9]{2})?$'),

  venue_id        text references public.venues (venue_id),
  home_team_id    text not null references public.teams (team_id),
  away_team_id    text not null references public.teams (team_id),
  home_goals      integer check (home_goals >= 0),
  away_goals      integer check (away_goals >= 0),

  -- The existing vocabulary, unchanged. The reporter UI displays "Full time"
  -- but publishes status='played' — there is deliberately no competing
  -- 'full_time' value, because standings, results and every renderer key off
  -- these six. played and awarded are what count toward a table.
  status          text not null
                  check (status in ('scheduled', 'played', 'postponed',
                                    'abandoned', 'awarded', 'cancelled')),

  -- Reserved for live reporting, which is NOT built. Kept off `status` so the
  -- existing vocabulary never has to grow a value the renderers don't know:
  -- a live match is still status='scheduled' with live_state set. Nothing
  -- reads this yet.
  live_state      text check (live_state in ('live', 'half_time')),

  awarded_note    text not null default '',

  -- Provenance, already in the model. Reporter submissions set
  -- source_type='reporter', reported_by and reported_at (see 0003).
  source_type     text not null default 'unknown'
                  check (source_type in ('reporter', 'rfa', 'fa', 'club',
                                         'facebook', 'newspaper', 'whatsapp',
                                         'backfill', 'placeholder', 'unknown')),
  source_ref      text not null default '',
  reported_by     text references public.reporters (reporter_id),
  reported_at     timestamptz,
  confidence      text not null default 'unconfirmed'
                  check (confidence in ('unconfirmed', 'confirmed', 'official')),
  verified_by     text references public.reporters (reporter_id),
  verified_at     timestamptz,

  -- Knockout-only. That they appear only on a cup, only on a tie's deciding
  -- leg, and only against a level score or aggregate are all cross-row rules
  -- and stay in validate.py check 7.
  extra_time      boolean not null default false,
  home_pens       integer check (home_pens >= 0),
  away_pens       integer check (away_pens >= 0),

  ord             bigint generated by default as identity,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  -- validate.py check 4, in full.
  constraint matches_no_self_play
    check (home_team_id <> away_team_id),
  constraint matches_score_is_a_pair
    check ((home_goals is null) = (away_goals is null)),
  constraint matches_played_has_score
    check (status not in ('played', 'awarded') or home_goals is not null),
  constraint matches_scheduled_has_no_score
    check (status <> 'scheduled' or home_goals is null),

  -- validate.py check 7, the parts that need only this row.
  constraint matches_pens_are_a_pair
    check ((home_pens is null) = (away_pens is null)),
  constraint matches_pens_have_a_winner
    check (home_pens is null or home_pens <> away_pens),

  -- validate.py check 3, now a database guarantee: a match cannot name a team
  -- that has no entries row for its competition+season. The plain FKs on
  -- home_team_id/away_team_id above are implied by these but kept, because a
  -- match referencing teams is a fact about the model, not an implementation
  -- detail of how entries happens to be keyed.
  constraint matches_home_team_entered
    foreign key (competition_id, season_id, home_team_id)
    references public.entries (competition_id, season_id, team_id),
  constraint matches_away_team_entered
    foreign key (competition_id, season_id, away_team_id)
    references public.entries (competition_id, season_id, team_id)
);

comment on column public.matches.public_id is
  'Deep-link id for /report/m/<public_id>. Not a capability: RLS authorizes.';
comment on column public.matches.live_state is
  'Reserved for live reporting; nothing reads it. Keeps status'' six values intact.';


-- ── goals ────────────────────────────────────────────────────────────────────
-- team_id is the team the goal COUNTED FOR — for an own goal that is the
-- beneficiary, with the defender as player_id. Own goals therefore never
-- appear in scorer tables but do count toward the score.

create table public.goals (
  goal_id              text primary key,
  match_id             text not null
                       references public.matches (match_id) on delete cascade,
  team_id              text not null references public.teams (team_id),
  player_id            text not null references public.players (player_id),

  -- The sheet's denormalized name column. The build ignores it entirely
  -- (names resolve via player_id -> players); it is carried over so the
  -- migration loses nothing, and it stays unread.
  player_name          text not null default '',

  -- NEW. What a reporter typed when EveryLeague has no canonical player yet.
  -- Paired with player_id = CAF_MW_UNKNOWN, so the goal counts toward the
  -- score and the name can be shown on the match page, while the scorer
  -- rankings — which already drop CAF_MW_UNKNOWN — stay canonical. Kept after
  -- reconciliation as provenance, hence no constraint tying it to UNKNOWN.
  reported_player_name text not null default '',

  -- Display string, not a number: '45+5' occurs in the data.
  minute               text not null default '',
  stoppage             text not null default '',
  period               text not null default ''
                       check (period in ('', '1h', '2h', 'et1', 'et2')),
  goal_type            text not null default ''
                       check (goal_type in ('', 'open_play', 'penalty',
                                            'free_kick', 'header', 'own_goal')),
  assist_player_id     text references public.players (player_id),
  source_type          text not null default 'unknown'
                       check (source_type in ('reporter', 'rfa', 'fa', 'club',
                                              'facebook', 'newspaper', 'whatsapp',
                                              'backfill', 'placeholder', 'unknown')),
  source_ref           text not null default '',
  reported_by          text references public.reporters (reporter_id),
  reported_at          timestamptz,
  confidence           text not null default 'unconfirmed'
                       check (confidence in ('unconfirmed', 'confirmed', 'official')),
  verified_by          text references public.reporters (reporter_id),
  verified_at          timestamptz,
  ord                  bigint generated by default as identity,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

comment on column public.goals.reported_player_name is
  'Reporter-typed scorer awaiting reconciliation. Display only — CAF_MW_UNKNOWN '
  'keeps it out of scorer rankings.';

-- That a match's goal rows never exceed its score, and that team_id actually
-- played in the match, are aggregate rules — validate.py check 5.


-- ── registrations ────────────────────────────────────────────────────────────
-- Currently empty. Key matches validate.PRIMARY_KEYS.

create table public.registrations (
  player_id      text not null references public.players (player_id),
  team_id        text not null references public.teams (team_id),
  season_id      text not null references public.seasons (season_id),
  shirt_number   text not null default '',
  from_date      date,
  to_date        date,
  ord            bigint generated by default as identity,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  primary key (player_id, team_id, season_id)
);


-- ── aliases ──────────────────────────────────────────────────────────────────
-- Alternate spellings, for matching incoming text to an entity. A duplicate
-- alias_text is legal (two clubs can share a nickname), so there is no natural
-- key — hence the surrogate id, matching validate.py, which checks these rows
-- for blank fields rather than uniqueness.

create table public.aliases (
  id           bigint generated by default as identity primary key,
  alias_text   text not null check (alias_text <> ''),
  entity_type  text not null check (entity_type <> ''),
  entity_id    text not null check (entity_id <> ''),
  context      text not null default '',
  ord          bigint not null,
  created_at   timestamptz not null default now()
);


-- ═══ National teams ══════════════════════════════════════════════════════════
-- A SEPARATE SCHEMA. These tables share no ids with the league tables above:
-- nt_teams.team_code (MW_W) is not teams.team_id, and national-team player ids
-- (MW_W_001) are their own namespace, absent from players. Nothing in the
-- league build path reads them. Do not add FKs across the boundary — the one
-- deliberate crossing is nt_squads.domestic_team_id.

create table public.nt_teams (
  team_code   text primary key,
  team_name   text not null check (team_name <> ''),
  category    text not null default '',
  ord         bigint generated by default as identity,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);


-- One row per match from OUR team's perspective: `opponent` is a display name,
-- not a code, so there is nothing to resolve it against.
create table public.nt_matches (
  match_id           text primary key,
  team_code          text not null references public.nt_teams (team_code),
  -- TEXT, not date: the literal 'tbd' is a legal value (6 rows today) meaning
  -- "fixture agreed, no date yet"; it renders as "Date TBC". Anything else
  -- must be strict YYYY-MM-DD.
  date               text not null default ''
                     check (date = '' or lower(date) in ('tbd', 'tba')
                            or date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'),
  competition        text not null default '',
  opponent           text not null default '',
  home_away          text not null default '',
  neutral            boolean not null default false,
  venue              text not null default '',
  -- Malawi time, like every other kickoff on the site.
  kickoff            text not null default ''
                     check (kickoff = '' or lower(kickoff) in ('tbd', 'tba')
                            or kickoff ~ '^[0-9]{1,2}:[0-9]{2}(:[0-9]{2})?$'),
  city               text not null default '',
  country            text not null default '',
  team_score         integer check (team_score >= 0),
  opponent_score     integer check (opponent_score >= 0),
  -- Narrower than the league vocabulary on purpose: no postponed/abandoned
  -- rows exist yet and nt_page has no rendering for them.
  status             text not null check (status in ('scheduled', 'played', 'awarded')),
  coach              text not null default '',
  extra_time         boolean not null default false,
  penalty_shootout   text not null default '',
  extra_time_result  text not null default '',
  ord                bigint generated by default as identity,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  constraint nt_matches_score_is_a_pair
    check ((team_score is null) = (opponent_score is null)),
  constraint nt_matches_played_has_score
    check (status not in ('played', 'awarded') or team_score is not null),
  constraint nt_matches_scheduled_has_no_score
    check (status <> 'scheduled' or team_score is null)
);


-- Holds BOTH sides' rows, told apart by team_id: ours is the nt_teams
-- team_code, the opponent's is a local label like NIGERIA_W with no row to
-- resolve against. So team_id deliberately has NO foreign key.
create table public.nt_goals (
  goal_id      text primary key,
  match_id     text not null
               references public.nt_matches (match_id) on delete cascade,
  team_id      text not null check (team_id <> ''),
  -- The opposite of the league rule: national-team scorer names come from
  -- here, because those player ids are not in the players table.
  player_name  text not null default '',
  player_id    text not null default '',
  minute       text not null default '',
  stoppage     text not null default '',
  period       text not null default '',
  -- Already display vocabulary here; the underscore form also parses.
  goal_type    text not null default ''
               check (goal_type in ('', 'penalty', 'own goal', 'own_goal')),
  assist_player_id text not null default '',
  source_type  text not null default '',
  source_ref   text not null default '',
  reported_by  text not null default '',
  reported_at  text not null default '',
  confidence   text not null default '',
  verified_by  text not null default '',
  verified_at  text not null default '',
  ord          bigint generated by default as identity,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on column public.nt_goals.team_id is
  'Ours = nt_teams.team_code; the opponent''s is a local label. No FK by design.';


-- One row per player per squad announcement. The current squad is the row
-- group sharing the most recent announcement_date.
create table public.nt_squads (
  squad_id             text not null,
  player_name          text not null check (player_name <> ''),
  competition          text not null default '',
  match_id_range       text not null default '',
  team_id              text not null references public.nt_teams (team_code),
  announcement_date    text not null default '',
  competition_context  text not null default '',
  player_id            text not null default '',
  position             text not null default '',
  shirt_number         text not null default '',
  club                 text not null default '',
  -- The ONE deliberate join back into the league schema, for the club-hub
  -- link. Blank for foreign-based players — expected, not an error. Left
  -- without an FK so a squad announcement never blocks on a missing team row.
  domestic_team_id     text not null default '',
  club_country         text not null default '',
  notes                text not null default '',
  coach                text not null default '',
  source_type          text not null default '',
  source_ref           text not null default '',
  reported_by          text not null default '',
  reported_at          text not null default '',
  confidence           text not null default '',
  verified_by          text not null default '',
  verified_at          text not null default '',
  ord                  bigint generated by default as identity,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  primary key (squad_id, player_name)
);


-- A hand-maintained group table, one row per team in the group, displayed
-- as-is. NEVER computed from matches, unlike a league table. A rival's row
-- carries its own team_name because it has no nt_teams row.
create table public.nt_competitions (
  team_code         text not null,
  competition_name  text not null check (competition_name <> ''),
  group_name        text not null default '',
  position          text not null default '',
  played            text not null default '',
  won               text not null default '',
  drawn             text not null default '',
  lost              text not null default '',
  points            text not null default '',
  last_update       text not null default '',
  wikipedia_url     text not null default '',
  team_name         text not null default '',
  goals_for         text not null default '',
  goals_against     text not null default '',
  ord               bigint generated by default as identity,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  primary key (team_code, competition_name)
);

comment on table public.nt_competitions is
  'Hand-maintained standings snapshot. Never derive it from nt_matches.';


create table public.nt_lineups (
  match_id         text not null
                   references public.nt_matches (match_id) on delete cascade,
  player_name      text not null check (player_name <> ''),
  -- Both sides again, so no FK (see nt_goals.team_id).
  team_id          text not null check (team_id <> ''),
  player_id        text not null default '',
  shirt_number     text not null default '',
  position         text not null default '',
  role             text not null check (role in ('starting', 'sub_on', 'unused_sub')),
  captain          boolean not null default false,
  minute_on        text not null default '',
  minute_off       text not null default '',
  replaced_player  text not null default '',
  yellow_card      boolean not null default false,
  yellow_red_card  boolean not null default false,
  red_card         boolean not null default false,
  ord              bigint generated by default as identity,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  primary key (match_id, player_name)
);

-- "At most 11 starters per side" and "sub_on names someone in this line-up"
-- are per-match aggregates — validate.py check 9.


-- Whole knockout trees, including ties we are not in (that is how the WAFCON
-- bracket renders). Our own ties additionally carry nt_match_id, and then
-- nt_matches owns the result — the score columns here must stay blank.
create table public.nt_knockout (
  tie_id            text primary key,
  competition_name  text not null check (competition_name <> ''),
  stage             text not null
                    check (stage in ('r64', 'r32', 'r16', 'qf', 'sf', 'final', '3p')),
  slot              integer not null default 0,
  home_name         text not null default '',
  away_name         text not null default '',
  -- 'winner:<tie_id>' / 'loser:<tie_id>' — a slot fed by an earlier tie. That
  -- the named tie exists, is not this one, and is in the same competition are
  -- cross-row rules in validate.py check 9.
  home_from         text not null default ''
                    check (home_from = '' or home_from ~ '^(winner|loser):.+$'),
  away_from         text not null default ''
                    check (away_from = '' or away_from ~ '^(winner|loser):.+$'),
  home_score        integer check (home_score >= 0),
  away_score        integer check (away_score >= 0),
  home_pens         integer check (home_pens >= 0),
  away_pens         integer check (away_pens >= 0),
  extra_time        boolean not null default false,
  date              text not null default '',
  kickoff           text not null default '',
  venue             text not null default '',
  city              text not null default '',
  status            text not null default 'scheduled'
                    check (status in ('scheduled', 'played', 'awarded')),
  nt_match_id       text references public.nt_matches (match_id),
  ord               bigint generated by default as identity,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint nt_knockout_score_is_a_pair
    check ((home_score is null) = (away_score is null)),
  constraint nt_knockout_pens_are_a_pair
    check ((home_pens is null) = (away_pens is null)),
  constraint nt_knockout_pens_have_a_winner
    check (home_pens is null or home_pens <> away_pens),
  -- nt_matches owns the result for our own ties, so a copy here could
  -- contradict it with nothing to say which is right (validate.py check 9).
  constraint nt_knockout_linked_tie_has_no_score
    check (nt_match_id is null
           or (home_score is null and away_score is null
               and home_pens is null and away_pens is null)),
  unique (competition_name, stage, slot)
);


-- ── Indexes ──────────────────────────────────────────────────────────────────
-- Every table is read whole, in ord order, by the build; the ord indexes serve
-- that. The rest serve the filters the site and the reporter app actually run.

create index clubs_ord_idx                on public.clubs (ord);
create index teams_ord_idx                on public.teams (ord);
create index teams_club_idx               on public.teams (club_id);
create index competitions_ord_idx         on public.competitions (ord);
create index seasons_ord_idx              on public.seasons (ord);
create index competition_seasons_ord_idx  on public.competition_seasons (ord);
create index entries_ord_idx              on public.entries (ord);
create index entries_comp_season_idx      on public.entries (competition_id, season_id);
create index venues_ord_idx               on public.venues (ord);
create index players_ord_idx              on public.players (ord);
create index reporters_ord_idx            on public.reporters (ord);
create index registrations_ord_idx        on public.registrations (ord);
create index aliases_ord_idx              on public.aliases (ord);

create index matches_ord_idx              on public.matches (ord);
-- The per-competition render loop, and the reporter's "today / upcoming".
create index matches_comp_season_idx      on public.matches (competition_id, season_id);
create index matches_date_idx             on public.matches (date) where date is not null;
create index matches_status_idx           on public.matches (status);
create index matches_home_team_idx        on public.matches (home_team_id);
create index matches_away_team_idx        on public.matches (away_team_id);
create index matches_venue_idx            on public.matches (venue_id);
create index matches_reported_by_idx      on public.matches (reported_by);

create index goals_ord_idx                on public.goals (ord);
create index goals_match_idx              on public.goals (match_id);
create index goals_player_idx             on public.goals (player_id);
create index goals_team_idx               on public.goals (team_id);

create index nt_teams_ord_idx             on public.nt_teams (ord);
create index nt_matches_ord_idx           on public.nt_matches (ord);
create index nt_matches_team_idx          on public.nt_matches (team_code);
create index nt_goals_ord_idx             on public.nt_goals (ord);
create index nt_goals_match_idx           on public.nt_goals (match_id);
create index nt_squads_ord_idx            on public.nt_squads (ord);
create index nt_competitions_ord_idx      on public.nt_competitions (ord);
create index nt_lineups_ord_idx           on public.nt_lineups (ord);
create index nt_lineups_match_idx         on public.nt_lineups (match_id);
create index nt_knockout_ord_idx          on public.nt_knockout (ord);


-- ── updated_at triggers ──────────────────────────────────────────────────────

do $$
declare t text;
begin
  foreach t in array array[
    'clubs', 'teams', 'competitions', 'seasons', 'competition_seasons',
    'entries', 'venues', 'players', 'reporters', 'matches', 'goals',
    'registrations', 'nt_teams', 'nt_matches', 'nt_goals', 'nt_squads',
    'nt_competitions', 'nt_lineups', 'nt_knockout'
  ] loop
    execute format(
      'create trigger %I before update on public.%I
         for each row execute function public.set_updated_at()',
      t || '_set_updated_at', t);
  end loop;
end;
$$;


-- ── Row Level Security ───────────────────────────────────────────────────────
-- On for every table. Reads are public for the football data the site shows;
-- reporters is excluded because it holds email and affiliation. NO write
-- policy exists yet, so through the Data API these tables are read-only to
-- everyone — the importer and CI write with the secret key, which bypasses
-- RLS. 0002 adds the reporter and admin policies.

alter table public.clubs                enable row level security;
alter table public.teams                enable row level security;
alter table public.competitions         enable row level security;
alter table public.seasons              enable row level security;
alter table public.competition_seasons  enable row level security;
alter table public.entries              enable row level security;
alter table public.venues               enable row level security;
alter table public.players              enable row level security;
alter table public.reporters            enable row level security;
alter table public.matches              enable row level security;
alter table public.goals                enable row level security;
alter table public.registrations        enable row level security;
alter table public.aliases              enable row level security;
alter table public.nt_teams             enable row level security;
alter table public.nt_matches           enable row level security;
alter table public.nt_goals             enable row level security;
alter table public.nt_squads            enable row level security;
alter table public.nt_competitions      enable row level security;
alter table public.nt_lineups           enable row level security;
alter table public.nt_knockout          enable row level security;

do $$
declare t text;
begin
  foreach t in array array[
    'clubs', 'teams', 'competitions', 'seasons', 'competition_seasons',
    'entries', 'venues', 'players', 'matches', 'goals', 'registrations',
    'aliases', 'nt_teams', 'nt_matches', 'nt_goals', 'nt_squads',
    'nt_competitions', 'nt_lineups', 'nt_knockout'
  ] loop
    execute format(
      'create policy %I on public.%I for select to anon, authenticated using (true)',
      t || '_public_read', t);
  end loop;
end;
$$;

commit;
