-- 0002_auth.sql — reporter identity and authorization.
--
-- The existing `reporters` entity IS the user model. Supabase Auth is bolted
-- onto it with auth_user_id rather than introducing a parallel profiles table:
-- matches.reported_by already points at reporter_id, and a second identity
-- concept would immediately need reconciling with it.
--
-- Authorization funnels through ONE function, public.can_report_match(). Every
-- policy and every future RPC asks it, so what "may report" means can grow
-- without touching the callers. That is what makes match-level assignment a
-- later addition rather than a redesign: add a reporter_match_assignments
-- table and one OR clause inside that function, and every policy inherits it.
--
-- Nothing here is readable by anon. Reporter identity, assignments and the
-- auth mapping are invisible to the public site, which reads only the football
-- data — the public build must stay byte-identical.

begin;

-- ── reporters gains an identity ──────────────────────────────────────────────

-- The table is empty (0 rows), so these are free operations. `active` becomes a
-- real boolean: authorization has to ask "is this reporter active?" on every
-- request and a free-text column cannot answer that reliably.
alter table public.reporters
  alter column active drop default,
  alter column active type boolean
    using (case when lower(nullif(active, '')) in ('1', 'true', 'yes', 'y', 'active')
                then true else false end),
  alter column active set default true,
  alter column active set not null;

alter table public.reporters
  -- on delete set null: deleting the login must not erase who reported a
  -- result. The reporters row is the attribution and outlives the account.
  add column auth_user_id uuid unique references auth.users (id) on delete set null,
  add column role text not null default 'reporter'
    check (role in ('reporter', 'admin'));

comment on column public.reporters.auth_user_id is
  'Maps this reporter to a Supabase Auth user. NULL = no login yet.';
comment on column public.reporters.role is
  'admin bypasses assignment checks (see is_admin). Set from the CLI only.';
comment on column public.reporters.active is
  'Inactive reporters keep their history but can no longer report anything.';

create index reporters_auth_user_idx on public.reporters (auth_user_id);


-- ── reporter_assignments ─────────────────────────────────────────────────────
-- What a reporter is allowed to report. Competition-level, which is how the
-- leagues are actually staffed: a reporter covers Northern Region Division One,
-- not a hand-picked list of fixtures.
--
-- season_id is nullable and means "every season of this competition". A season
-- can therefore be scoped without a schema change when a reporter is taken off
-- a competition at season end.
--
-- FOR MATCH-LEVEL ASSIGNMENT LATER: do not add a discriminator here. Create
-- reporter_match_assignments (reporter_id, match_id) and add one OR clause to
-- can_report_match(). This table keeps its meaning and no policy changes.

create table public.reporter_assignments (
  id              bigint generated by default as identity primary key,
  reporter_id     text not null
                  references public.reporters (reporter_id) on delete cascade,
  competition_id  text not null
                  references public.competitions (competition_id) on delete cascade,
  season_id       text references public.seasons (season_id) on delete cascade,
  created_at      timestamptz not null default now(),
  -- A NULL season_id does not collide with itself under a plain UNIQUE, so the
  -- all-seasons row is pinned by its own partial index below.
  unique (reporter_id, competition_id, season_id)
);

create unique index reporter_assignments_all_seasons
  on public.reporter_assignments (reporter_id, competition_id)
  where season_id is null;

-- Both columns are read on every authorization check.
create index reporter_assignments_reporter_idx
  on public.reporter_assignments (reporter_id);
create index reporter_assignments_competition_idx
  on public.reporter_assignments (competition_id, season_id);

comment on table public.reporter_assignments is
  'Competition-level reporting rights. season_id NULL = all seasons.';


-- ── Authorization helpers ────────────────────────────────────────────────────
-- All three are SECURITY DEFINER for one specific reason: RLS on `reporters`
-- would otherwise recurse. A policy on reporters that calls a function that
-- reads reporters re-enters the policy forever. SECURITY DEFINER runs the body
-- as the owner, outside RLS, breaking the cycle.
--
-- The safety conditions that makes acceptable, applied to each:
--   * `set search_path = ''` so no schema can be shadowed by a caller;
--   * every object fully qualified (public.x, auth.uid());
--   * each returns only a boolean or the caller's OWN reporter_id — none is a
--     generic privileged reader, and none takes a query as input;
--   * EXECUTE is granted to authenticated only, never to anon.
--
-- `(select auth.uid())` rather than a bare auth.uid() so Postgres evaluates it
-- once per statement as an InitPlan instead of once per row.

create or replace function public.current_reporter_id()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select r.reporter_id
  from public.reporters r
  where r.auth_user_id = (select auth.uid())
    and r.active
$$;

comment on function public.current_reporter_id() is
  'The signed-in reporter, or NULL when there is none or they are inactive.';


create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.reporters r
    where r.auth_user_id = (select auth.uid())
      and r.active
      and r.role = 'admin'
  )
$$;


create or replace function public.can_report_match(p_match_id text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_admin() or exists (
    select 1
    from public.matches m
    join public.reporter_assignments a
      on a.competition_id = m.competition_id
     -- NULL season_id = every season of the competition.
     and (a.season_id is null or a.season_id = m.season_id)
    join public.reporters r
      on r.reporter_id = a.reporter_id
    where m.match_id = p_match_id
      and r.auth_user_id = (select auth.uid())
      and r.active
  )
$$;

comment on function public.can_report_match(text) is
  'The single authorization question. Extend HERE for match-level assignment.';


-- anon must never reach these. An unauthenticated visitor has no reporter
-- identity by definition, and leaving them callable would let anyone probe
-- which matches a session can report.
revoke execute on function public.current_reporter_id() from public, anon;
revoke execute on function public.is_admin() from public, anon;
revoke execute on function public.can_report_match(text) from public, anon;
grant execute on function public.current_reporter_id() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.can_report_match(text) to authenticated;


-- ── RLS ──────────────────────────────────────────────────────────────────────
-- reporters already had RLS enabled in 0001 with no policy at all, so it has
-- been readable only by the secret key. That stays true for anon; a signed-in
-- reporter additionally gets their own row, which is what /report needs to
-- greet them by name.

alter table public.reporter_assignments enable row level security;

create policy reporters_read_own
  on public.reporters for select to authenticated
  using (auth_user_id = (select auth.uid()) or public.is_admin());

create policy reporter_assignments_read_own
  on public.reporter_assignments for select to authenticated
  using (reporter_id = public.current_reporter_id() or public.is_admin());

-- Deliberately NO insert/update/delete policy on either table. Creating
-- reporters, granting competitions and deactivating people are CLI operations
-- run with the secret key, which bypasses RLS. There is no admin portal and
-- no path by which a signed-in user can grant themselves anything.
--
-- Public signup is disabled in the project's Auth settings, but this schema
-- does not depend on that: a brand-new auth.users row with no reporters row
-- resolves to a NULL current_reporter_id() and can therefore do nothing at all.

commit;
