-- 0003_reporting.sql — the write path, and the record of it.
--
-- This is the ONLY way a reporter can change a match. There is deliberately no
-- UPDATE policy on public.matches: being authorized to report a result is not
-- permission to edit the row, and the difference matters. A generic UPDATE
-- would let anyone who can report a score also swap the teams, move the
-- fixture into another season, or rewrite its kickoff. This function touches
-- four columns and derives the rest.
--
-- It is SECURITY DEFINER because it must write past RLS — that is the point,
-- and it is safe only because the function is narrow: fixed parameters, no
-- dynamic SQL, every object fully qualified, an empty search_path, and EXECUTE
-- granted to authenticated only.
--
-- CONFIDENCE POLICY. The site already renders `confidence = 'unconfirmed'` as
-- an asterisk with a "result not yet confirmed" legend on the by-date pages
-- (src/matches_page.py). That is exactly the right signal for a grassroots
-- result phoned in from the touchline, so:
--
--     a reporter's submission  -> confidence = 'unconfirmed'
--     an admin's submission    -> confidence = 'confirmed', and the admin is
--                                 recorded in verified_by/verified_at
--
-- An admin is an editor with authority; their word is the verification. A
-- reporter's result publishes immediately either way — it is marked, not held.

begin;

-- ── match_change_log ─────────────────────────────────────────────────────────
-- Append-only. A reporter correcting 2-1 to 2-2 must not destroy the knowledge
-- that 2-1 was published first, and by whom.

create table public.match_change_log (
  id           bigint generated by default as identity primary key,
  match_id     text not null references public.matches (match_id) on delete cascade,
  -- Nullable so that deleting a reporter cannot delete history; the row keeps
  -- saying what changed even when it can no longer say who.
  changed_by   text references public.reporters (reporter_id) on delete set null,
  changed_at   timestamptz not null default now(),
  old_values   jsonb not null,
  new_values   jsonb not null,
  -- How the change arrived. Everything is 'reporter' today; a future bulk
  -- correction or import can say so without being mistaken for a person.
  source       text not null default 'reporter'
);

create index match_change_log_match_idx on public.match_change_log (match_id, changed_at desc);
create index match_change_log_changed_by_idx on public.match_change_log (changed_by);

comment on table public.match_change_log is
  'Append-only audit of published match changes. No UPDATE or DELETE is granted '
  'to any role through the API.';

alter table public.match_change_log enable row level security;

-- Operational data, not public: an anonymous visitor sees the current result on
-- the site and has no business reading who changed what. A reporter sees the
-- history of matches they are responsible for, which is what makes a correction
-- explainable; an admin sees everything.
create policy match_change_log_read
  on public.match_change_log for select to authenticated
  using (public.is_admin() or public.can_report_match(match_id));

-- No insert/update/delete policy at all. The log is written only by
-- submit_match_report, which runs as the owner and so bypasses RLS. Belt and
-- braces against a future policy making the table writable by accident:
revoke insert, update, delete on public.match_change_log from anon, authenticated;


-- ── submit_match_report ──────────────────────────────────────────────────────

create or replace function public.submit_match_report(
  p_match_id   text,
  p_home_score integer,
  p_away_score integer,
  p_status     text
)
returns setof public.matches
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_reporter text;
  v_is_admin boolean;
  v_match    public.matches;
  v_old      jsonb;
  v_new      jsonb;
  v_scored   boolean;
begin
  -- 1. Authenticated.
  if (select auth.uid()) is null then
    raise exception 'not authenticated'
      using errcode = '28000';
  end if;

  -- 2. A live reporter identity. current_reporter_id() already requires
  --    reporters.active, so a deactivated account fails here even though its
  --    login still works.
  v_reporter := public.current_reporter_id();
  if v_reporter is null then
    raise exception 'reporter account is inactive or not linked'
      using errcode = '42501';
  end if;

  -- 3. The match must exist. Locked for the rest of the transaction so two
  --    reporters publishing the same match serialize instead of racing, and
  --    the audit rows come out in the order the changes actually happened.
  select * into v_match
  from public.matches
  where match_id = p_match_id
  for update;

  if not found then
    raise exception 'match not found'
      using errcode = 'P0002';
  end if;

  -- 4. Authorized for THIS match. The same question the UI asks, asked again
  --    where it counts — the client is not trusted.
  if not public.can_report_match(p_match_id) then
    raise exception 'not assigned to this competition'
      using errcode = '42501';
  end if;

  v_is_admin := public.is_admin();

  -- 5. Validate. These mirror validate.py check 4 and the table's own
  --    constraints; catching them here produces a message a reporter can act
  --    on rather than a constraint-violation code.
  if p_status not in ('scheduled', 'played', 'postponed', 'abandoned',
                      'cancelled', 'awarded') then
    raise exception 'invalid status %', p_status
      using errcode = '22023';
  end if;

  -- 'awarded' is an administrative decision — a walkover, a forfeit — not
  -- something observed at a ground. It counts into standings with its recorded
  -- score, so it stays out of the reporter path.
  if p_status = 'awarded' and not v_is_admin then
    raise exception 'only an administrator can record an awarded result'
      using errcode = '42501';
  end if;

  v_scored := p_status in ('played', 'awarded');

  if v_scored then
    if p_home_score is null or p_away_score is null then
      raise exception 'invalid score: a % result needs both scores', p_status
        using errcode = '22023';
    end if;
    if p_home_score < 0 or p_away_score < 0
       or p_home_score > 99 or p_away_score > 99 then
      raise exception 'invalid score: goals must be between 0 and 99'
        using errcode = '22023';
    end if;
  else
    -- A fixture that was not played carries no score. Rejecting rather than
    -- silently discarding: if the client sent one, the two disagree about what
    -- is being published and the reporter should see that.
    if p_home_score is not null or p_away_score is not null then
      raise exception 'invalid score: a % match cannot carry a score', p_status
        using errcode = '22023';
    end if;
  end if;

  v_old := jsonb_build_object(
    'home_goals', v_match.home_goals,
    'away_goals', v_match.away_goals,
    'status',     v_match.status);
  v_new := jsonb_build_object(
    'home_goals', p_home_score,
    'away_goals', p_away_score,
    'status',     p_status);

  -- 6. Write ONLY the reporting fields. home_team_id, away_team_id,
  --    competition_id, season_id, date, kickoff, venue_id and every other
  --    structural column are absent from this statement by design.
  update public.matches
  set home_goals  = p_home_score,
      away_goals  = p_away_score,
      status      = p_status,
      source_type = 'reporter',
      reported_by = v_reporter,
      reported_at = now(),
      confidence  = case when v_is_admin then 'confirmed' else 'unconfirmed' end,
      verified_by = case when v_is_admin then v_reporter else v_match.verified_by end,
      verified_at = case when v_is_admin then now() else v_match.verified_at end,
      updated_at  = now()
  where match_id = p_match_id
  returning * into v_match;

  -- 7. Record it — but only when something actually changed. Re-tapping
  --    publish on an unchanged result is a no-op worth attributing (steps 6
  --    still update reported_by/reported_at) and not worth a log row.
  if v_old is distinct from v_new then
    insert into public.match_change_log
      (match_id, changed_by, old_values, new_values)
    values (p_match_id, v_reporter, v_old, v_new);
  end if;

  return next v_match;
end;
$$;

comment on function public.submit_match_report(text, integer, integer, text) is
  'The only reporter write path to matches. Updates score/status only, sets '
  'provenance, and appends to match_change_log.';

revoke execute on function public.submit_match_report(text, integer, integer, text)
  from public, anon;
grant execute on function public.submit_match_report(text, integer, integer, text)
  to authenticated;

commit;
