-- 0018_lineups.sql — league and cup team sheets, and they reach the site.
--
-- WHAT WAS WRONG. A national-team match can carry a team sheet: nt_lineups is
-- part of the dataset, src/nt_page.py renders it, and /scorchers/results.html
-- has had a Line-up toggle since 0012. A league match could not. The /report
-- screen for a league match offered four separate accordions — Goalscorers,
-- Cards, Substitutions, Line-ups — writing to goals, match_incidents and
-- lineup_entries, and of those only goals is part of the Dataset. Everything a
-- reporter typed into the other three was stored correctly and then rendered
-- nowhere at all, which from the reporter's side is indistinguishable from the
-- feature not working. Both tables held zero rows when this was written, so
-- nothing has been lost and there is nothing to migrate.
--
-- WHAT THIS DOES. public.lineups is nt_lineups' shape, column for column, so
-- that src/lineups.py can fold and render both from one implementation rather
-- than two that drift. Three deliberate differences, all of them because a
-- league match has two REAL teams where an NT match has ours and a name:
--
--   * team_id is a genuine FK to teams, and is in the primary key. nt_lineups
--     can key on (match_id, player_name) because only our own side is ever
--     stored; here both sides are, and two clubs may field players who share a
--     name.
--   * player_id is a genuine FK to players. On the NT side it was a private
--     MW_W_### namespace pointing at nothing; every id in the dataset is a
--     players row now.
--   * the sheet is guarded by can_report_match(), the same funnel every other
--     league write already goes through, rather than can_edit_nt().
--
-- WHAT THE VALIDATOR STILL HAS TO DO. As with 0012, the single-row rules are
-- the database's job and it does them below. The cross-row half — no more than
-- eleven starters per side, a sub_on carrying a minute, a replaced_player who
-- is actually on that side's sheet, a team_id that is one of the match's two
-- teams — is checked here at write time AND in validate.py at build time. Here
-- so a reporter is told immediately; there because a row can also arrive by
-- import, and one bad row must never be able to stop every future build.

begin;

-- ── lineups ──────────────────────────────────────────────────────────────────

create table public.lineups (
  match_id         text not null
                   references public.matches (match_id) on delete cascade,
  team_id          text not null references public.teams (team_id),
  -- The name AS REPORTED, exactly as goals.reported_player_name: it is what
  -- someone typed, and it stays readable even if the id is later repointed.
  player_name      text not null check (player_name <> ''),
  -- Blank means "not identified yet" — the same state an unresolved scorer
  -- sits in. Blank cannot be an FK, so the FK lives on a nullable column and
  -- the CSV reconstruction renders NULL as "".
  player_id        text references public.players (player_id),
  shirt_number     text not null default '',
  -- Optional here where nt_lineups requires it: a league sheet routinely
  -- arrives as eleven names off a Facebook photo with no positions at all.
  position         text not null default ''
                   check (position in ('', 'GK', 'DF', 'MF', 'FW')),
  role             text not null check (role in ('starting', 'sub_on', 'unused_sub')),
  captain          boolean not null default false,
  minute_on        text not null default '',
  minute_off       text not null default '',
  replaced_player  text not null default '',
  yellow_card      boolean not null default false,
  yellow_red_card  boolean not null default false,
  red_card         boolean not null default false,
  source_type      text not null default 'reporter',
  reported_by      text references public.reporters (reporter_id),
  ord              bigint generated by default as identity,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  primary key (match_id, team_id, player_name),
  -- A substitute who came on has to say when. Enforced per row here; the
  -- cross-row half of the same rule is below and in validate.py.
  constraint lineups_sub_has_minute
    check (role <> 'sub_on' or minute_on <> ''),
  -- A second yellow IS a red, so the two cannot be recorded as separate
  -- straight cards on the same player.
  constraint lineups_card_states
    check (not (yellow_red_card and red_card))
);

comment on table public.lineups is
  'One row per named player per side per match: the starting XI, the bench, '
  'who came on for whom, the cards and the armband. The league counterpart of '
  'nt_lineups, deliberately the same shape.';
comment on column public.lineups.player_name is
  'The name as reported. player_id is who that turned out to be.';
comment on column public.lineups.replaced_player is
  'A NAME, not an id — the sheet is written and read by name.';

create index lineups_ord_idx     on public.lineups (ord);
create index lineups_match_idx   on public.lineups (match_id);
create index lineups_player_idx  on public.lineups (player_id);

create trigger lineups_set_updated_at before update on public.lineups
  for each row execute function public.set_updated_at();

alter table public.lineups enable row level security;
create policy lineups_public_read on public.lineups
  for select to anon, authenticated using (true);


-- ── the two tables this replaces ─────────────────────────────────────────────
-- Left in place rather than dropped: they are empty, dropping them is a
-- separate decision, and a comment is what stops the next reader wiring a new
-- screen to them. /report stops writing to both in the same change.

comment on table public.lineup_entries is
  'DEPRECATED — superseded by public.lineups (0018). Never part of the '
  'Dataset, so nothing written here ever rendered. Do not add writes.';
comment on table public.match_incidents is
  'DEPRECATED — cards and substitutions are columns on public.lineups (0018), '
  'because they belong to a player on a team sheet rather than to a free '
  'floating event. Never part of the Dataset. Do not add writes.';


-- ── save_lineup ──────────────────────────────────────────────────────────────
-- One side's whole sheet in one call, delete-then-insert, exactly as
-- save_nt_lineup. A team sheet is edited as a whole because that is how it is
-- read: sending thirteen individual upserts would leave a half-saved XI
-- visible whenever one of them failed.

create or replace function public.save_lineup(
  p_match_id text,
  p_team_id  text,
  p_rows     jsonb
)
returns setof public.lineups
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_match    public.matches;
  v_names    text[];
  v_starting integer;
  v_row      jsonb;
  v_ord      integer := 0;
begin
  select * into v_match from public.matches
  where match_id = p_match_id for update;
  if not found then
    raise exception 'match not found' using errcode = 'P0002';
  end if;
  if not public.can_report_match(p_match_id) then
    raise exception 'you are not assigned to that match' using errcode = '42501';
  end if;
  -- A sheet belongs to one of the two teams that played. Without this a typo
  -- files eleven players under a club that was not there, and the FK above
  -- would happily accept it.
  if p_team_id is distinct from v_match.home_team_id
     and p_team_id is distinct from v_match.away_team_id then
    raise exception 'that team did not play in this match' using errcode = '22023';
  end if;
  if jsonb_typeof(p_rows) <> 'array' then
    raise exception 'the line-up must be a list' using errcode = '22023';
  end if;

  select array_agg(btrim(r->>'player_name')) into v_names
  from jsonb_array_elements(p_rows) r;
  v_names := coalesce(v_names, '{}');

  if exists (select 1 from unnest(v_names) n where coalesce(n, '') = '') then
    raise exception 'every line-up row needs a player name' using errcode = '22023';
  end if;
  -- The primary key would reject a repeat anyway — said here because
  -- "duplicate key" is not a sentence a reporter can act on.
  if (select count(distinct n) from unnest(v_names) n) <> array_length(v_names, 1) then
    raise exception 'the same player is listed twice' using errcode = '22023';
  end if;

  select count(*) into v_starting
  from jsonb_array_elements(p_rows) r where r->>'role' = 'starting';
  if v_starting > 11 then
    raise exception 'a starting XI is eleven players, not %', v_starting
      using errcode = '22023';
  end if;

  for v_row in select * from jsonb_array_elements(p_rows) loop
    if coalesce(v_row->>'role', '') not in ('starting', 'sub_on', 'unused_sub') then
      raise exception 'invalid line-up role %', coalesce(v_row->>'role', '')
        using errcode = '22023';
    end if;
    if v_row->>'role' = 'sub_on'
       and btrim(coalesce(v_row->>'minute_on', '')) = '' then
      raise exception 'a substitute who came on needs the minute (%)',
        v_row->>'player_name' using errcode = '22023';
    end if;
    if btrim(coalesce(v_row->>'replaced_player', '')) <> ''
       and not (btrim(v_row->>'replaced_player') = any (v_names)) then
      raise exception
        'replaced player % is not in this line-up', v_row->>'replaced_player'
        using errcode = '22023';
    end if;
    if btrim(coalesce(v_row->>'player_id', '')) <> ''
       and not exists (select 1 from public.players p
                       where p.player_id = btrim(v_row->>'player_id')) then
      raise exception 'unknown player id %', v_row->>'player_id'
        using errcode = '22023';
    end if;
    -- A second yellow IS a red, so a row cannot hold both. Said here as well
    -- as in the CHECK constraint because "violates check constraint
    -- lineups_card_states" is not a sentence a reporter can act on.
    if coalesce((v_row->>'yellow_red_card')::boolean, false)
       and coalesce((v_row->>'red_card')::boolean, false) then
      raise exception
        '% cannot have a second yellow AND a straight red', v_row->>'player_name'
        using errcode = '22023';
    end if;
  end loop;

  delete from public.lineups
  where match_id = p_match_id and team_id = p_team_id;

  for v_row in select * from jsonb_array_elements(p_rows) loop
    v_ord := v_ord + 1;
    insert into public.lineups (
      match_id, team_id, player_name, player_id, shirt_number, position,
      role, captain, minute_on, minute_off, replaced_player,
      yellow_card, yellow_red_card, red_card, reported_by, ord
    ) values (
      p_match_id, p_team_id, btrim(v_row->>'player_name'),
      nullif(btrim(coalesce(v_row->>'player_id', '')), ''),
      btrim(coalesce(v_row->>'shirt_number', '')),
      upper(btrim(coalesce(v_row->>'position', ''))),
      v_row->>'role',
      coalesce((v_row->>'captain')::boolean, false),
      btrim(coalesce(v_row->>'minute_on', '')),
      btrim(coalesce(v_row->>'minute_off', '')),
      btrim(coalesce(v_row->>'replaced_player', '')),
      coalesce((v_row->>'yellow_card')::boolean, false),
      coalesce((v_row->>'yellow_red_card')::boolean, false),
      coalesce((v_row->>'red_card')::boolean, false),
      public.current_reporter_id(),
      v_ord
    );
  end loop;

  -- Same derivation 0013 added to the NT sheet: whoever a substitute replaced
  -- came off when that substitute came on. After the insert because it reads
  -- across the sheet, and only where minute_off was left blank so an
  -- explicitly recorded departure — a sending-off, a withdrawal with nobody
  -- replacing them — still wins.
  update public.lineups off_row
  set minute_off = sub.minute_on,
      updated_at = now()
  from public.lineups sub
  where off_row.match_id = p_match_id
    and off_row.team_id  = p_team_id
    and off_row.minute_off = ''
    and sub.match_id = p_match_id
    and sub.team_id  = p_team_id
    and sub.role = 'sub_on'
    and sub.minute_on <> ''
    and sub.replaced_player = off_row.player_name;

  return query
    select * from public.lineups
    where match_id = p_match_id and team_id = p_team_id order by ord;
end;
$$;

comment on function public.save_lineup(text, text, jsonb) is
  'Replace one side''s whole team sheet for one match. Cross-row rules are '
  'checked before anything is written; minute_off is derived from the '
  'substitutions afterwards.';

revoke execute on function public.save_lineup(text, text, jsonb)
  from public, anon;
grant execute on function public.save_lineup(text, text, jsonb)
  to authenticated;

commit;
