-- 0024_officials_registry.sql — the referee is a person, not a string.
--
-- WHAT 0023 SAID, AND WHY IT CHANGED. Eight days ago this schema put the
-- referee and both coaches on the match as free text, and argued the case in
-- its own header: "an officials table would be the right shape if this site
-- tracked referees as people — a referee's profile, matches refereed, cards
-- shown. It does not, and building the join table for a feature nobody asked
-- for would mean every reporter typing a name now has to resolve it to an id."
-- That was the right call for the data that existed then. It is wrong now,
-- because the feature was asked for: a page per referee listing every match
-- they took, and the same for a coach. The last line of that header was
-- "if a referee ever needs a page, the strings are already there to seed it
-- from", and this is that.
--
-- WHAT THIS DOES. One registry, `officials`, and six id columns on matches
-- beside the six text columns 0023 added. The text columns stay, and stay
-- meaning exactly what they meant: THE NAME AS REPORTED. The id is who that
-- name turned out to be. It is the identical arrangement to
-- lineups.player_name + lineups.player_id, deliberately, so that
--
--   * a name nobody has resolved yet still saves and still renders — a
--     reporter is at a touchline and must never be blocked by a registry;
--   * an identified name renders through the registry, so ONE rename moves
--     every page that names them (see 0022, the same rule for players);
--   * the archive of what was actually typed survives underneath both.
--
-- ONE TABLE, TWO KINDS, and this is the part worth arguing. A referee, an
-- assistant referee and a fourth official are not three professions; they are
-- one person taking a different job on a different Saturday, and in Malawi
-- they rotate through all three within a season. Separate `referees` and
-- `assistants` tables would split one career across three rows. So the four
-- match-official roles share one pool, and `kind` separates that pool from the
-- coaches, who really are different people doing a different thing —
-- search_officials filters on it, so a coach is never offered as a referee.
--
-- The table is called `officials` although it holds coaches too, which is a
-- small lie of naming. The alternative — `people`, or two tables — costs more
-- than the lie does: every operation here (mint, search, rename, merge, list
-- their matches) is identical for both kinds, and the site's own dataclass
-- has been called Officials since 0023.
--
-- WHAT THIS DOES NOT DO. It does not backfill. The six text columns hold
-- whatever has been typed so far and those matches keep rendering plain text
-- until someone opens the match in /report and taps the name onto a registry
-- row. Matching those strings automatically is exactly the merge risk 0020
-- wrote about at length, for a handful of rows, and a wrong referee is a
-- falsehood about a real person.

begin;

-- ── officials ────────────────────────────────────────────────────────────────
-- Deliberately as narrow as `players`: an id, a name, and what kind of person
-- they are. No association, no level, no card counts — those are things
-- someone standing at a pitch does not know and must not be asked to guess.

create table if not exists public.officials (
  official_id  text primary key,
  full_name    text not null check (full_name <> ''),
  -- The name they are known by, when it differs from the full one. Same
  -- three-valued handling as players.known_as in rename_official below.
  known_as     text not null default '',
  -- referee covers the whole match-official pool: referee, either assistant,
  -- fourth official. One person, one row, whichever job they took that day.
  kind         text not null check (kind in ('referee', 'coach')),
  status       text not null default 'active',
  reported_by  text references public.reporters (reporter_id),
  ord          bigint generated by default as identity,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.officials is
  'Referees and coaches as identities. One pool for all four match-official '
  'roles, because the same person referees one match and runs the line at the '
  'next; kind separates them from coaches. Reporters add a row through '
  'create_official() — a deliberate tap, never a side effect of saving a '
  'match. A name nobody has resolved stays free text on matches.';

alter table public.officials enable row level security;
create policy officials_public_read on public.officials
  for select to anon, authenticated using (true);


-- ── the six id columns ───────────────────────────────────────────────────────
-- Nullable, because blank cannot be an FK — the same shape lineups.player_id
-- has for the same reason, and the CSV reconstruction renders NULL as "".
--
-- Six columns rather than a match_officials(match_id, role, official_id) join
-- table: the roles are a closed set of exactly six, one person each, and the
-- join table would buy nothing but a group-by on every read. matches already
-- carries the six names; these sit beside them.
--
-- NOT constrained to a kind. Postgres cannot check "referee_id must point at a
-- row whose kind = referee" without a composite key or a trigger, and the
-- portal only ever offers the right pool. A coach mis-tapped into the referee
-- box is a data-entry mistake, fixable in the portal, not a corruption.

alter table public.matches
  add column if not exists referee_id             text references public.officials (official_id),
  add column if not exists assistant_referee_1_id text references public.officials (official_id),
  add column if not exists assistant_referee_2_id text references public.officials (official_id),
  add column if not exists fourth_official_id     text references public.officials (official_id),
  add column if not exists home_coach_id          text references public.officials (official_id),
  add column if not exists away_coach_id          text references public.officials (official_id);

comment on column public.matches.referee_id is
  'Who the referee turned out to be. NULL means the name in matches.referee '
  'has not been resolved to a registry row — which is normal and renders as '
  'plain text, exactly as an unidentified team-sheet name does.';

-- Every read of an official page is "every match this person took", and that
-- is six columns' worth of OR. Six small partial indexes, each skipping the
-- overwhelming majority of rows where the column is NULL.
create index if not exists matches_referee_id_idx
  on public.matches (referee_id) where referee_id is not null;
create index if not exists matches_assistant_referee_1_id_idx
  on public.matches (assistant_referee_1_id) where assistant_referee_1_id is not null;
create index if not exists matches_assistant_referee_2_id_idx
  on public.matches (assistant_referee_2_id) where assistant_referee_2_id is not null;
create index if not exists matches_fourth_official_id_idx
  on public.matches (fourth_official_id) where fourth_official_id is not null;
create index if not exists matches_home_coach_id_idx
  on public.matches (home_coach_id) where home_coach_id is not null;
create index if not exists matches_away_coach_id_idx
  on public.matches (away_coach_id) where away_coach_id is not null;


-- ── next_official_id ─────────────────────────────────────────────────────────
-- MW_OFF_000001 and up. Country prefix and underscores, like every other id in
-- this schema; the digits are a counter and carry no meaning. Players use a
-- CAF_ prefix because that registry is confederation-wide in principle — this
-- one is not, so it takes the MW_ prefix clubs, teams and matches use.

create or replace function public.next_official_id()
returns text
language sql
security definer
set search_path = ''
as $$
  select 'MW_OFF_' || lpad(
    (coalesce(
      (select max(substring(o.official_id from 8)::int)
       from public.officials o
       where o.official_id ~ '^MW_OFF_[0-9]{6}$'),
      0) + 1)::text, 6, '0');
$$;

revoke execute on function public.next_official_id() from public, anon, authenticated;


-- ── create_official ──────────────────────────────────────────────────────────
-- Idempotent on (name, kind), case-insensitively, exactly as create_player is
-- on the name: two reporters typing "H. Nkhoma" on two different matches on
-- the same Saturday must end up pointing at one person, or the whole point of
-- the id is lost. The kind is part of the key because a coach and a referee
-- who share a name are two people, and this is the one place that distinction
-- is cheap to keep.

create or replace function public.create_official(
  p_full_name text,
  p_kind      text
)
returns setof public.officials
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_reporter text;
  v_name     text;
  v_kind     text;
  v_official public.officials;
begin
  v_reporter := public.current_reporter_id();
  if v_reporter is null then
    raise exception 'reporter account is inactive or not linked'
      using errcode = '42501';
  end if;

  -- Collapse runs of whitespace as well as trimming, as create_player does:
  -- "H.  Nkhoma" and "H. Nkhoma" are one person and the difference is
  -- invisible on screen.
  v_name := btrim(regexp_replace(coalesce(p_full_name, ''), '\s+', ' ', 'g'));
  v_kind := lower(btrim(coalesce(p_kind, '')));

  if v_kind not in ('referee', 'coach') then
    raise exception 'kind must be referee or coach' using errcode = '22023';
  end if;
  if length(v_name) < 2 then
    raise exception 'an official needs a name' using errcode = '22023';
  end if;
  if length(v_name) > 80 then
    raise exception 'that name is too long' using errcode = '22023';
  end if;

  select * into v_official
  from public.officials o
  where o.kind = v_kind
    and (lower(o.full_name) = lower(v_name)
         or (o.known_as <> '' and lower(o.known_as) = lower(v_name)))
  order by o.ord
  limit 1;
  if found then
    return next v_official;
    return;
  end if;

  insert into public.officials (official_id, full_name, kind, status, reported_by)
  values (public.next_official_id(), v_name, v_kind, 'active', v_reporter)
  returning * into v_official;

  return next v_official;
end;
$$;

comment on function public.create_official(text, text) is
  'Mint or find an official by name and kind. Idempotent on both, so two '
  'reporters typing the same referee get the same id.';

revoke execute on function public.create_official(text, text) from public, anon;
grant execute on function public.create_official(text, text) to authenticated;


-- ── rename_official ──────────────────────────────────────────────────────────
-- The other half of create_official, and open to the same reporters, for the
-- reason 0022 gave for rename_player: the graphic says "H. Nkhoma" and the
-- first name turns up a week later. Renaming is reversible; only merging is
-- not, and only merging is admin-only.
--
-- The previous spelling goes to `aliases` under entity_type 'official', which
-- is what makes search_officials find them by what they used to be called.

create or replace function public.rename_official(
  p_official_id text,
  p_full_name   text,
  p_known_as    text default null
)
returns setof public.officials
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_reporter text;
  v_name     text;
  v_known    text;
  v_old      public.officials;
  v_new      public.officials;
begin
  v_reporter := public.current_reporter_id();
  if v_reporter is null then
    raise exception 'reporter account is inactive or not linked'
      using errcode = '42501';
  end if;

  select * into v_old from public.officials o
  where o.official_id = p_official_id for update;
  if not found then
    raise exception 'official not found' using errcode = 'P0002';
  end if;

  v_name := btrim(regexp_replace(coalesce(p_full_name, ''), '\s+', ' ', 'g'));
  if length(v_name) < 2 then
    raise exception 'an official needs a name' using errcode = '22023';
  end if;
  if length(v_name) > 80 then
    raise exception 'that name is too long' using errcode = '22023';
  end if;

  -- Renaming INTO a name someone of the same kind already answers to would
  -- make create_official return one of them forever and hide the other. Same
  -- refusal, and the same advice, as rename_player.
  if exists (
    select 1 from public.officials o
    where o.official_id <> p_official_id
      and o.kind = v_old.kind
      and (lower(o.full_name) = lower(v_name)
           or (o.known_as <> '' and lower(o.known_as) = lower(v_name)))
  ) then
    raise exception 'there is already a % called % — merge them instead',
      v_old.kind, v_name using errcode = '23505';
  end if;

  -- Computed before the UPDATE rather than as a CASE inside it, the way
  -- rename_player does it: three-valued means NULL leaves the nickname alone
  -- and '' clears it, and that reads plainly only when it is one statement.
  v_known := case when p_known_as is null then v_old.known_as
                  else btrim(regexp_replace(p_known_as, '\s+', ' ', 'g'))
             end;

  update public.officials o
  set full_name  = v_name,
      known_as   = v_known,
      updated_at = now()
  where o.official_id = p_official_id
  returning * into v_new;

  -- Keep every spelling this person has been filed under. ord is `not null`
  -- with no default on aliases (0001), so it is computed rather than defaulted.
  if lower(v_old.full_name) <> lower(v_new.full_name)
     and not exists (
       select 1 from public.aliases a
       where a.entity_type = 'official' and a.entity_id = p_official_id
         and lower(a.alias_text) = lower(v_old.full_name)) then
    insert into public.aliases (alias_text, entity_type, entity_id, context, ord)
    values (v_old.full_name, 'official', p_official_id, 'renamed',
            coalesce((select max(a.ord) from public.aliases a), 0) + 1);
  end if;

  return next v_new;
end;
$$;

comment on function public.rename_official(text, text, text) is
  'Correct an official''s name. The old spelling is kept in aliases, which is '
  'what search_officials reads. p_known_as is three-valued: NULL leaves it, '
  '''''  clears it.';

revoke execute on function public.rename_official(text, text, text) from public, anon;
grant execute on function public.rename_official(text, text, text) to authenticated;


-- ── merge_officials ──────────────────────────────────────────────────────────
-- Two ids turn out to be one person. Admin-only, because it DELETES a row —
-- the same permission split, for the same reason, as merge_players.
--
-- Far simpler than merging players: an official is named on exactly six
-- columns of one table, so there is no cross-table repointing and no collision
-- to resolve. A match cannot end up with the same person twice in one role,
-- because each column holds one id.

create or replace function public.merge_officials(
  p_loser  text,
  p_winner text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_loser   public.officials;
  v_winner  public.officials;
  v_matches int := 0;
  v_one     int;
  v_col     text;
begin
  if not public.is_admin() then
    raise exception 'only an admin can merge officials' using errcode = '42501';
  end if;
  if p_loser = p_winner then
    raise exception 'those are the same official' using errcode = '22023';
  end if;

  -- Locked in id order, so the mirror-image call cannot deadlock against this
  -- one. Same rule as merge_players.
  perform 1 from public.officials o
  where o.official_id in (p_loser, p_winner)
  order by o.official_id for update;

  select * into v_loser from public.officials o where o.official_id = p_loser;
  if not found then
    raise exception 'official % not found', p_loser using errcode = 'P0002';
  end if;
  select * into v_winner from public.officials o where o.official_id = p_winner;
  if not found then
    raise exception 'official % not found', p_winner using errcode = 'P0002';
  end if;
  if v_loser.kind <> v_winner.kind then
    raise exception 'a % and a % are not the same person',
      v_loser.kind, v_winner.kind using errcode = '22023';
  end if;

  foreach v_col in array array[
    'referee_id', 'assistant_referee_1_id', 'assistant_referee_2_id',
    'fourth_official_id', 'home_coach_id', 'away_coach_id'
  ] loop
    execute format(
      'update public.matches set %I = $1 where %I = $2', v_col, v_col)
      using p_winner, p_loser;
    get diagnostics v_one = row_count;
    v_matches := v_matches + v_one;
  end loop;

  -- The loser's spellings outlive the loser: they are how someone typing the
  -- old name still finds the person it belonged to.
  update public.aliases a
  set entity_id = p_winner
  where a.entity_type = 'official' and a.entity_id = p_loser;

  if not exists (
    select 1 from public.aliases a
    where a.entity_type = 'official' and a.entity_id = p_winner
      and lower(a.alias_text) = lower(v_loser.full_name)) then
    insert into public.aliases (alias_text, entity_type, entity_id, context, ord)
    values (v_loser.full_name, 'official', p_winner, 'merged',
            coalesce((select max(a.ord) from public.aliases a), 0) + 1);
  end if;

  delete from public.officials o where o.official_id = p_loser;

  return jsonb_build_object(
    'winner', p_winner, 'loser', p_loser, 'matches', v_matches);
end;
$$;

comment on function public.merge_officials(text, text) is
  'Fold one official into another and delete the loser. Admin-only: it '
  'deletes a row and cannot be undone from the portal.';

revoke execute on function public.merge_officials(text, text) from public, anon;
grant execute on function public.merge_officials(text, text) to authenticated;


-- ── search_officials ─────────────────────────────────────────────────────────
-- Line for line the ranking search_players uses, and for the same reason: the
-- name that gets typed first is the one off a graphic ("H. Nkhoma"), the full
-- name turns up later, and somebody searching "Hassan Nkhoma" has to find the
-- row that already exists instead of minting a second one. Substring, then an
-- alias (a spelling they used to be filed under), then the surname with
-- agreeing initials.
--
-- p_kind is required, not optional. Every caller knows which box it is filling
-- in, and a referee picker that offers coaches is how the wrong kind of person
-- ends up in the wrong column.

create or replace function public.search_officials(
  p_term text,
  p_kind text
)
returns table (
  official_id text,
  full_name   text,
  known_as    text,
  matched     text,
  score       int
)
language sql
stable
security definer
set search_path = ''
as $$
  with parts as (
    select t, lower(t) as lt,
           lower(split_part(t, ' ', greatest(1, array_length(string_to_array(t, ' '), 1))))
             as surname,
           lower(left(t, 1)) as initial,
           k
    from (
      select btrim(regexp_replace(coalesce(p_term, ''), '\s+', ' ', 'g')) as t,
             lower(btrim(coalesce(p_kind, ''))) as k
    ) raw
  ),
  candidates as (
    select o.official_id, o.full_name, o.known_as,
           lower(coalesce(nullif(o.known_as, ''), o.full_name)) as label,
           lower(split_part(
             coalesce(nullif(o.known_as, ''), o.full_name), ' ',
             greatest(1, array_length(string_to_array(
               coalesce(nullif(o.known_as, ''), o.full_name), ' '), 1)))) as surname,
           lower(left(coalesce(nullif(o.known_as, ''), o.full_name), 1)) as initial
    from public.officials o, parts x
    where o.kind = x.k and x.k in ('referee', 'coach')
      and o.status <> 'inactive'
  ),
  hits as (
    select c.official_id, c.full_name, c.known_as, '' as matched,
           case when c.label = x.lt then 100
                when c.label like x.lt || '%' then 80
                else 60 end as score
    from candidates c, parts x
    where x.lt <> '' and (lower(c.full_name) like '%' || x.lt || '%'
                          or lower(c.known_as) like '%' || x.lt || '%')
    union all
    select c.official_id, c.full_name, c.known_as, a.alias_text as matched, 50
    from candidates c
    join public.aliases a
      on a.entity_type = 'official' and a.entity_id = c.official_id
    cross join parts x
    where x.lt <> '' and lower(a.alias_text) like '%' || x.lt || '%'
    union all
    -- Guarded on a surname of three characters or more: below that it is an
    -- initial or a particle and matches half the country.
    select c.official_id, c.full_name, c.known_as, '' as matched, 30
    from candidates c, parts x
    where length(x.surname) >= 3
      and c.surname = x.surname
      and (x.initial = c.initial
           or x.surname = x.lt
           or c.surname = c.label)
  )
  select h.official_id, h.full_name, h.known_as,
         (array_agg(h.matched order by h.score desc))[1] as matched,
         max(h.score)::integer as score
  from hits h
  group by h.official_id, h.full_name, h.known_as
  order by max(h.score) desc, h.full_name
  limit 12;
$$;

comment on function public.search_officials(text, text) is
  'Official lookup for the reporter portal, one kind at a time: substring, '
  'alias, then surname with agreeing initials, ranked. Finds "Hassan Nkhoma" '
  'when the match-day post said "H. Nkhoma".';

revoke execute on function public.search_officials(text, text) from public;
grant execute on function public.search_officials(text, text)
  to anon, authenticated;


-- ── set_match_officials, twelve columns wide ─────────────────────────────────
-- Replaces the seven-argument version from 0023. Dropped and recreated rather
-- than overloaded: two functions of the same name where every argument has a
-- default is ambiguous to a named-argument call, which is the only way the
-- portal calls it.
--
-- THE DEPLOY WINDOW IS SAFE. Every new argument defaults to '', so a phone
-- still running the pre-0024 app.js — which sends the seven old arguments by
-- name — resolves to this function and clears six id columns that are empty
-- anyway. A migration is a separate deploy from git (see CLAUDE.md); this is
-- what makes the gap between them harmless rather than a broken save.
--
-- ALL TWELVE VALUES ARE SENT EVERY TIME and a blank one clears its column, for
-- the reason 0023 gave: the portal submits the whole panel as one save, so
-- "not sent" and "cleared" would be the same keystroke.
--
-- An id is written only if it exists in the registry; anything else is
-- discarded and the name alone is kept. That is deliberately silent — a
-- reporter who typed a name and never tapped a suggestion gets exactly what
-- they would have got before this migration, which is the whole graceful
-- degradation rule.

drop function if exists public.set_match_officials(
  text, text, text, text, text, text, text);

create or replace function public.set_match_officials(
  p_match_id                text,
  p_referee                 text default '',
  p_assistant_referee_1     text default '',
  p_assistant_referee_2     text default '',
  p_fourth_official         text default '',
  p_home_coach              text default '',
  p_away_coach              text default '',
  p_referee_id              text default '',
  p_assistant_referee_1_id  text default '',
  p_assistant_referee_2_id  text default '',
  p_fourth_official_id      text default '',
  p_home_coach_id           text default '',
  p_away_coach_id           text default ''
)
returns setof public.matches
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_reporter text;
  v_match    public.matches;
  v_new      public.matches;
  v_vals     text[];
  v_ids      text[];
  v_one      text;
  v_i        int;
begin
  v_reporter := public.current_reporter_id();
  if v_reporter is null then
    raise exception 'reporter account is inactive or not linked'
      using errcode = '42501';
  end if;

  select * into v_match from public.matches m
  where m.match_id = p_match_id for update;
  if not found then
    raise exception 'match not found' using errcode = 'P0002';
  end if;

  if not public.can_report_match(p_match_id) then
    raise exception 'not assigned to this competition' using errcode = '42501';
  end if;

  v_vals := array[
    btrim(regexp_replace(coalesce(p_referee, ''), '\s+', ' ', 'g')),
    btrim(regexp_replace(coalesce(p_assistant_referee_1, ''), '\s+', ' ', 'g')),
    btrim(regexp_replace(coalesce(p_assistant_referee_2, ''), '\s+', ' ', 'g')),
    btrim(regexp_replace(coalesce(p_fourth_official, ''), '\s+', ' ', 'g')),
    btrim(regexp_replace(coalesce(p_home_coach, ''), '\s+', ' ', 'g')),
    btrim(regexp_replace(coalesce(p_away_coach, ''), '\s+', ' ', 'g'))
  ];
  foreach v_one in array v_vals loop
    if length(v_one) > 80 then
      raise exception 'that name is too long' using errcode = '22023';
    end if;
  end loop;

  v_ids := array[
    btrim(coalesce(p_referee_id, '')),
    btrim(coalesce(p_assistant_referee_1_id, '')),
    btrim(coalesce(p_assistant_referee_2_id, '')),
    btrim(coalesce(p_fourth_official_id, '')),
    btrim(coalesce(p_home_coach_id, '')),
    btrim(coalesce(p_away_coach_id, ''))
  ];
  -- An id with no name beside it would render as nothing at all on a site that
  -- reads the text column when there is no id and the registry when there is.
  -- An unknown id is dropped rather than refused, for the reason above.
  for v_i in 1..6 loop
    if v_ids[v_i] <> '' and (
         v_vals[v_i] = ''
         or not exists (select 1 from public.officials o
                        where o.official_id = v_ids[v_i])) then
      v_ids[v_i] := '';
    end if;
  end loop;

  if (v_match.referee, v_match.assistant_referee_1, v_match.assistant_referee_2,
      v_match.fourth_official, v_match.home_coach, v_match.away_coach,
      v_match.referee_id, v_match.assistant_referee_1_id,
      v_match.assistant_referee_2_id, v_match.fourth_official_id,
      v_match.home_coach_id, v_match.away_coach_id)
     is not distinct from
     (v_vals[1], v_vals[2], v_vals[3], v_vals[4], v_vals[5], v_vals[6],
      nullif(v_ids[1], ''), nullif(v_ids[2], ''), nullif(v_ids[3], ''),
      nullif(v_ids[4], ''), nullif(v_ids[5], ''), nullif(v_ids[6], '')) then
    return next v_match;
    return;
  end if;

  update public.matches m
  set referee                = v_vals[1],
      assistant_referee_1    = v_vals[2],
      assistant_referee_2    = v_vals[3],
      fourth_official        = v_vals[4],
      home_coach             = v_vals[5],
      away_coach             = v_vals[6],
      referee_id             = nullif(v_ids[1], ''),
      assistant_referee_1_id = nullif(v_ids[2], ''),
      assistant_referee_2_id = nullif(v_ids[3], ''),
      fourth_official_id     = nullif(v_ids[4], ''),
      home_coach_id          = nullif(v_ids[5], ''),
      away_coach_id          = nullif(v_ids[6], ''),
      updated_at             = now()
  where m.match_id = p_match_id
  returning * into v_new;

  insert into public.match_change_log
    (match_id, changed_by, old_values, new_values)
  values (
    p_match_id, v_reporter,
    jsonb_build_object('referee', v_match.referee,
                       'assistant_referee_1', v_match.assistant_referee_1,
                       'assistant_referee_2', v_match.assistant_referee_2,
                       'fourth_official', v_match.fourth_official,
                       'home_coach', v_match.home_coach,
                       'away_coach', v_match.away_coach,
                       'referee_id', v_match.referee_id,
                       'assistant_referee_1_id', v_match.assistant_referee_1_id,
                       'assistant_referee_2_id', v_match.assistant_referee_2_id,
                       'fourth_official_id', v_match.fourth_official_id,
                       'home_coach_id', v_match.home_coach_id,
                       'away_coach_id', v_match.away_coach_id),
    jsonb_build_object('referee', v_vals[1],
                       'assistant_referee_1', v_vals[2],
                       'assistant_referee_2', v_vals[3],
                       'fourth_official', v_vals[4],
                       'home_coach', v_vals[5],
                       'away_coach', v_vals[6],
                       'referee_id', nullif(v_ids[1], ''),
                       'assistant_referee_1_id', nullif(v_ids[2], ''),
                       'assistant_referee_2_id', nullif(v_ids[3], ''),
                       'fourth_official_id', nullif(v_ids[4], ''),
                       'home_coach_id', nullif(v_ids[5], ''),
                       'away_coach_id', nullif(v_ids[6], '')));

  return next v_new;
end;
$$;

comment on function public.set_match_officials(
  text, text, text, text, text, text, text,
  text, text, text, text, text, text) is
  'Referee, assistants, fourth official and both coaches — the name as '
  'reported and, where the reporter tapped one, the registry id it belongs '
  'to. Writes those twelve columns only; a blank argument clears its column, '
  'because the portal sends the whole panel as one save.';

revoke execute on function public.set_match_officials(
  text, text, text, text, text, text, text,
  text, text, text, text, text, text) from public, anon;
grant execute on function public.set_match_officials(
  text, text, text, text, text, text, text,
  text, text, text, text, text, text) to authenticated;

commit;
