-- 0052_portal_errors.sql — a screen that breaks should say so somewhere.
--
-- WHAT WAS WRONG. #/add threw a TypeError on every draw from 5 September to 6
-- October. Not intermittently and not for some reporters: the fixture form was
-- dead for everybody, in every competition, for a month. Nothing recorded it,
-- nothing counted it, and nobody reported it — because of HOW it failed rather
-- than how badly. The first draw painted "Loading teams…", the throw landed on
-- the second, and the spinner stayed. On the connection this app is written
-- for, a spinner that never resolves is not a broken screen. It is Tuesday.
--
-- That is the failure mode worth building against. An error message a reporter
-- can see gets mentioned; a screen that merely never finishes does not, and
-- the portal has no way at all of noticing on its own. Every screen added
-- since can fail exactly the same way.
--
-- WHAT THIS DOES. One table, one write path, one admin view. The client
-- installs window.onerror and unhandledrejection handlers, dedupes, and calls
-- record_portal_error — and separately stops leaving a spinner up, which is
-- the half a reporter actually experiences.
--
-- WHAT IT DELIBERATELY IS NOT. Not analytics, not a session recorder, not a
-- log of what anyone did. Four columns: where it happened, what was thrown,
-- the stack, and the browser. No page contents, no inputs, no navigation
-- history. The question this exists to answer is "is a screen broken right
-- now", and anything else it collected would be a thing to have to justify.
--
-- NOT WRITABLE BY anon, so an error on the sign-in screen is not recorded.
-- That is a real gap and it is the right trade: the alternative is an
-- unauthenticated insert endpoint on a public database, and the screens that
-- matter are the ones behind the login anyway.

begin;

create table public.portal_errors (
  id          bigint generated by default as identity primary key,

  -- Nullable for match_change_log.changed_by's reason: deleting a reporter
  -- must not delete the evidence that a screen was broken.
  reporter_id text references public.reporters (reporter_id) on delete set null,

  -- The hash route, '/add' or '/ops', which is the single most useful field:
  -- it is the name of the screen to go and look at.
  route       text not null default '',
  message     text not null default '',
  stack       text not null default '',
  user_agent  text not null default '',
  created_at  timestamptz not null default now()
);

create index portal_errors_recent_idx on public.portal_errors (created_at desc);
create index portal_errors_route_idx on public.portal_errors (route, created_at desc);

comment on table public.portal_errors is
  'Uncaught errors from /report. Four columns and no page contents — it exists '
  'to answer "is a screen broken", and nothing else.';

alter table public.portal_errors enable row level security;

-- Admin only, and not even the reporter who hit it: a stack trace is an
-- operational artefact, and a reporter who sees one has been given something
-- to worry about that they cannot act on. An unhandled rejection from a failed
-- RPC can also carry the sentence Postgres raised, which may name a team — the
-- same reason report_imports is not public.
create policy portal_errors_read
  on public.portal_errors for select to authenticated
  using (public.is_admin());

-- No insert policy, deliberately. Rows come only from the function below,
-- which enforces the cap. A generic INSERT grant on a table anyone signed in
-- can write to is a way to fill a database.
revoke insert, update, delete on public.portal_errors from anon, authenticated;


-- ── record_portal_error ──────────────────────────────────────────────────────
-- IT NEVER RAISES. Every other RPC in this schema refuses bad input with a
-- sentence a reporter can act on; this one is called FROM an error handler, and
-- an error handler that can itself fail is a loop with a database at the bottom
-- of it. Over the cap, unauthenticated, malformed — it returns quietly and the
-- browser goes on.
--
-- The cap is per reporter per hour and it is the whole safety story. The
-- failure this prevents is not abuse: it is a render loop throwing the same
-- TypeError sixty times a second, which is exactly the shape of the bug that
-- prompted the table. The client dedupes as well, and neither of those is
-- trusted to be the only one that works.

create or replace function public.record_portal_error(
  p_route      text default '',
  p_message    text default '',
  p_stack      text default '',
  p_user_agent text default ''
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_reporter text;
  v_recent   integer;
begin
  if (select auth.uid()) is null then
    return;
  end if;
  v_reporter := public.current_reporter_id();
  if v_reporter is null then
    return;
  end if;

  select count(*) into v_recent
  from public.portal_errors e
  where e.reporter_id = v_reporter
    and e.created_at > now() - interval '1 hour';
  if v_recent >= 20 then
    return;
  end if;

  -- Truncated rather than refused, for the same reason as above: a stack from
  -- a deep call chain is long, and a report that arrives shortened is worth
  -- immeasurably more than one that does not arrive.
  insert into public.portal_errors
    (reporter_id, route, message, stack, user_agent)
  values (
    v_reporter,
    left(btrim(coalesce(p_route, '')), 100),
    left(btrim(coalesce(p_message, '')), 500),
    left(btrim(coalesce(p_stack, '')), 2000),
    left(btrim(coalesce(p_user_agent, '')), 300));
exception
  when others then
    -- Belt to the braces. Whatever went wrong recording an error, it must not
    -- become a second error on top of the first.
    return;
end;
$$;

comment on function public.record_portal_error(text, text, text, text) is
  'Record an uncaught error from /report. Never raises and never blocks — it '
  'is called from an error handler. Capped at 20 an hour per reporter.';

revoke execute on function public.record_portal_error(text, text, text, text)
  from public, anon;
grant execute on function public.record_portal_error(text, text, text, text)
  to authenticated;


-- ── ops_portal_errors ────────────────────────────────────────────────────────
-- GROUPED, because the answer to "is a screen broken" is one row per broken
-- screen. #/add would have been ONE line here — "/add · Cannot read properties
-- of undefined (reading 'status') · 340 times · 11 reporters · first seen 5
-- September" — and no amount of scrolling through 340 identical rows would
-- have said it better.
--
-- security_invoker with is_admin() in the body: 0016's arrangement, and the
-- revoke from anon that 0047 forgot and 0048 had to add.

create or replace view public.ops_portal_errors with (security_invoker = true) as
select
  e.route,
  e.message,
  count(*)                                   as hits,
  count(distinct e.reporter_id)              as reporters,
  min(e.created_at)                          as first_seen,
  max(e.created_at)                          as last_seen,
  -- One example stack. They are the same error, so the first one explains all
  -- of them, and 340 copies of it would explain no more.
  (array_agg(e.stack order by e.created_at desc))[1] as stack
from public.portal_errors e
group by e.route, e.message
having public.is_admin();

comment on view public.ops_portal_errors is
  'One row per broken screen: where, what, how often, how many people, and '
  'since when. Admin only.';

revoke all on public.ops_portal_errors from anon;
grant select on public.ops_portal_errors to authenticated;

commit;
